# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
{fetchNuGet}: [
  (fetchNuGet {
    pname = "ApiSurface";
    version = "4.0.43";
    sha256 = "0bx09n3c751vz7v39pcdm6zb8k5p01fzc2vlclgkxg4nj38mmvh8";
  })
  (fetchNuGet {
    pname = "fantomas";
    version = "6.3.9";
    sha256 = "1b34iiiff02bbzjv03zyna8xmrgs6y87zdvp5i5k58fcqpjw44sx";
  })
  (fetchNuGet {
    pname = "FsCheck";
    version = "3.0.0-rc3";
    sha256 = "1rn4x9qh479927viwww3dy0mikcdcq3pfqv1hzbbawnwxfzm17z1";
  })
  (fetchNuGet {
    pname = "fsharp-analyzers";
    version = "0.26.0";
    sha256 = "0xgv5kvbwfdvcp6s8x7xagbbi4s3mqa4ixni6pazqvyflbgnah7b";
  })
  (fetchNuGet {
    pname = "FSharp.Core";
    version = "6.0.0";
    sha256 = "1hjhvr39c1vpgrdmf8xln5q86424fqkvy9nirkr29vl2461d2039";
  })
  (fetchNuGet {
    pname = "FSharp.Core";
    version = "8.0.300";
    sha256 = "158xxr9hnhz2ibyzzp2d249angvxfc58ifflm4g3hz8qx9zxaq04";
  })
  (fetchNuGet {
    pname = "FsUnit";
    version = "6.0.0";
    sha256 = "18q3p0z155znwj1l0qq3vq9nh9wl2i4mlfx4pmrnia4czr0xdkmb";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Ref";
    version = "6.0.31";
    sha256 = "0hki4z9x60vzcg53s8cxnig4g1xnpqcj629r2cg5q1xw0sknfp5d";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.linux-arm64";
    version = "6.0.31";
    sha256 = "0blf8hl2irl9r9x6f7cih87ps21rcs3b8r09z5wp7jcb5j1cv8fg";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.linux-x64";
    version = "6.0.31";
    sha256 = "050dzfy49c4jwcm8dfrz2lqbbyhmgnq485zdhpcnc3w08z0ppbs6";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.osx-arm64";
    version = "6.0.31";
    sha256 = "0w4sab66rjjyar9z139ls6rx29gvgj3rp3cbrsc8z00y9mw2sl22";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.osx-x64";
    version = "6.0.31";
    sha256 = "13kww7x35926wik32z8cnvzhpqp3dwhazkzb569v87x8yww56n3k";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeCoverage";
    version = "17.10.0";
    sha256 = "0s0v7jmrq85n356xv7zixvwa4z94fszjcr5vll8x4im1a2lp00f9";
  })
  (fetchNuGet {
    pname = "Microsoft.NET.Test.Sdk";
    version = "17.10.0";
    sha256 = "13g8fwl09li8fc71nk13dgkb7gahd4qhamyg2xby7am63nlchhdf";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.linux-arm64";
    version = "6.0.31";
    sha256 = "05s1c6bd4592xhy0y3w0cjckg11hb4pci729v59k3i3hl0hbad4s";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.linux-x64";
    version = "6.0.31";
    sha256 = "10s0p30qzfn9zibp1ldnqar87hqs47ni3rwqpvwx4jn3589cl9sn";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.osx-arm64";
    version = "6.0.31";
    sha256 = "0sah1gf2lccc93n3lmkgiahlz4jwr02cw20bvcwqyikpldy2awds";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.osx-x64";
    version = "6.0.31";
    sha256 = "0k16h1fwnvhw1gcx8ib01bidhrls5m56fiy6wldk3ajgs5dif8i6";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Ref";
    version = "6.0.31";
    sha256 = "19a4ainxj8jxij7ckglbmlnvrjxp72xfgx0r6lbglzh9dhsakwm7";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.linux-arm64";
    version = "6.0.31";
    sha256 = "1wmlwzy9bc1fs38r0vpn3ragp8pkimcq6sicj978yhk7brn52z1p";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.linux-x64";
    version = "6.0.31";
    sha256 = "0pw2n3j6vbmbghda1cvkhi3c39a49xk0a4w059mfya017adl6kac";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.osx-arm64";
    version = "6.0.31";
    sha256 = "115c220p0mbk30biaw0sfqprnaghks7lcvvz6n5rsg0kn4fvy7qs";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.osx-x64";
    version = "6.0.31";
    sha256 = "1cl561dgdk4mj48zw5xwg7a0cafkx8j2wjd4nlv0x3di300k75k5";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "2.0.0";
    sha256 = "1fk2fk2639i7nzy58m9dvpdnzql4vb8yl8vr19r2fp8lmj9w2jr0";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.ObjectModel";
    version = "17.10.0";
    sha256 = "07j69cw8r39533w4p39mnj00kahazz38760in3jfc45kmlcdb26x";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.TestHost";
    version = "17.10.0";
    sha256 = "1bl471s7fx9jycr0cc8rylwf34mrvlg9qn1an6l86nisavfcyb7v";
  })
  (fetchNuGet {
    pname = "Myriad.Sdk";
    version = "0.8.3";
    sha256 = "0qv78c5s5m04xb8h17nnn2ig26zcyya91k2dpj745cm1cbnzvvgc";
  })
  (fetchNuGet {
    pname = "Nerdbank.GitVersioning";
    version = "3.6.139";
    sha256 = "0npcryhq3r0c2zi940jk39h13mzc4hyg7z8gm6jdmxi1aqv1vh8c";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.1";
    sha256 = "0fijg0w6iwap8gvzyjnndds0q4b8anwxxvik7y8vgq97dram4srb";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.3";
    sha256 = "0xrwysmrn4midrjal8g2hr1bbg38iyisl0svamb11arqws4w2bw7";
  })
  (fetchNuGet {
    pname = "NuGet.Common";
    version = "6.10.1";
    sha256 = "1z69k0j727jcwrxzmvnixdac84lb9706iabqs8mrns8j7kbmw1ns";
  })
  (fetchNuGet {
    pname = "NuGet.Configuration";
    version = "6.10.1";
    sha256 = "0qy2bdi3dz6fdw7qbv77fg956idm9d9733j8b1pcrcj9pfayys26";
  })
  (fetchNuGet {
    pname = "NuGet.Frameworks";
    version = "6.10.1";
    sha256 = "1p8d701fhbqv2r8vqmj948af9xvz2fd3273803cdrjy3a2wykmq1";
  })
  (fetchNuGet {
    pname = "NuGet.Packaging";
    version = "6.10.1";
    sha256 = "0zl8xfzvd1yij2ln6iwy6cz8qfwlbyyqlin872ab5y58ws61a2x2";
  })
  (fetchNuGet {
    pname = "NuGet.Protocol";
    version = "6.10.1";
    sha256 = "0zw5q1pn74qa1mcxx5268nklx18442s76x70dlqan4pm9kbvzr2i";
  })
  (fetchNuGet {
    pname = "NuGet.Versioning";
    version = "6.10.1";
    sha256 = "0lji7g6abnpmhzlgvni8wlb7l62n4180v3sphp4494wi0gn7ds4c";
  })
  (fetchNuGet {
    pname = "NUnit";
    version = "4.1.0";
    sha256 = "0fj6xwgqaxq3mrai86bklclfmjkzf038mrslwfqf4ignaz9f7g5j";
  })
  (fetchNuGet {
    pname = "NUnit3TestAdapter";
    version = "4.5.0";
    sha256 = "1srx1629s0k1kmf02nmz251q07vj6pv58mdafcr5dr0bbn1fh78i";
  })
  (fetchNuGet {
    pname = "Spectre.Console";
    version = "0.49.1";
    sha256 = "0fhl96p3xjd5k1wwvhs80cp35rrlgnza6mw9vy0knhmf7ji9b95n";
  })
  (fetchNuGet {
    pname = "System.Formats.Asn1";
    version = "6.0.0";
    sha256 = "1vvr7hs4qzjqb37r0w1mxq7xql2b17la63jwvmgv65s1hj00g8r9";
  })
  (fetchNuGet {
    pname = "System.IO.Abstractions";
    version = "4.2.13";
    sha256 = "0s784iphsmj4vhkrzq9q3w39vsn76w44zclx3hsygsw458zbyh4y";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem.AccessControl";
    version = "4.5.0";
    sha256 = "1gq4s8w7ds1sp8f9wqzf8nrzal40q5cd2w4pkf4fscrl2ih3hkkj";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "1.6.0";
    sha256 = "1wdbavrrkajy7qbdblpbpbalbdl48q3h34cchz24gvdgyrlf15r4";
  })
  (fetchNuGet {
    pname = "System.Security.AccessControl";
    version = "4.5.0";
    sha256 = "1wvwanz33fzzbnd2jalar0p0z3x0ba53vzx1kazlskp7pwyhlnq0";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Pkcs";
    version = "6.0.4";
    sha256 = "0hh5h38pnxmlrnvs72f2hzzpz4b2caiiv6xf8y7fzdg84r3imvfr";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.ProtectedData";
    version = "4.4.0";
    sha256 = "1q8ljvqhasyynp94a1d7jknk946m20lkwy2c3wa8zw2pc517fbj6";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "4.5.0";
    sha256 = "0rmj89wsl5yzwh0kqjgx45vzf694v9p92r4x4q6yxldk1cv1hi86";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "7.0.0";
    sha256 = "1151hbyrcf8kyg1jz8k9awpbic98lwz9x129rg7zk1wrs6vjlpxl";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "7.0.3";
    sha256 = "0zjrnc9lshagm6kdb9bdh45dmlnkpwcpyssa896sda93ngbmj8k9";
  })
  (fetchNuGet {
    pname = "WoofWare.DotnetRuntimeLocator";
    version = "0.1.9";
    sha256 = "14yc3ixcn58wy0v3pbj0hjfj4iv5k1ckig0dg1n7njx30510kzyj";
  })
  (fetchNuGet {
    pname = "WoofWare.Myriad.Plugins";
    version = "2.1.52";
    sha256 = "03cx16c9zhc2yjldrks4kfh8xx3x757zjhjk98sd7i8q7s6agqyn";
  })
  (fetchNuGet {
    pname = "WoofWare.Myriad.Plugins.Attributes";
    version = "3.1.8";
    sha256 = "0xhgl5kkw5hn15ghry3k0w7h4v2d6aww9dmpb7j49aims1r6c76c";
  })
  (fetchNuGet {
    pname = "WoofWare.PrattParser";
    version = "0.2.2";
    sha256 = "0cgrmd1kc3k224lsjhy5npalwg6kpqd8nx78szi1yq67kyb0farq";
  })
]
